//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pymex.Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntradaProducto
    {
        public int EntradaProductoID { get; set; }
        public int EntradaID { get; set; }
        public int ProductoID { get; set; }
        public decimal PrecioCompraUnidad { get; set; }
        public decimal PrecioVentaUnidad { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Entrada Entrada { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
