//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pymex.Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.EntradaProducto = new HashSet<EntradaProducto>();
            this.SalidaProducto = new HashSet<SalidaProducto>();
        }
    
        public int ProductoID { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public short CategoriaID { get; set; }
        public short AlmacenID { get; set; }
        public bool Activo { get; set; }
        public Nullable<decimal> UltimoPrecioCompra { get; set; }
        public Nullable<decimal> UltimoPrecioVenta { get; set; }
        public Nullable<int> Stock { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string UsuarioRegistro { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UltimoUsuarioModifico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntradaProducto> EntradaProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalidaProducto> SalidaProducto { get; set; }
        public virtual Almacen Almacen { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}
