//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pymex.Services.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PymexEntities : DbContext
    {
        public PymexEntities()
            : base("name=PymexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sistema> Sistema { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Permiso> Permiso { get; set; }
        public virtual DbSet<Entrada> Entrada { get; set; }
        public virtual DbSet<EntradaProducto> EntradaProducto { get; set; }
        public virtual DbSet<Salida> Salida { get; set; }
        public virtual DbSet<SalidaProducto> SalidaProducto { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Almacen> Almacen { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
    
        public virtual ObjectResult<usp_ObtenerResumen_Result> usp_ObtenerResumen(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenerResumen_Result>("usp_ObtenerResumen", fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual int usp_RegistrarEntrada(Nullable<System.DateTime> fechaRegistro, string usuarioRegistro, Nullable<int> proveedorId, string productos)
        {
            var fechaRegistroParameter = fechaRegistro.HasValue ?
                new ObjectParameter("fechaRegistro", fechaRegistro) :
                new ObjectParameter("fechaRegistro", typeof(System.DateTime));
    
            var usuarioRegistroParameter = usuarioRegistro != null ?
                new ObjectParameter("usuarioRegistro", usuarioRegistro) :
                new ObjectParameter("usuarioRegistro", typeof(string));
    
            var proveedorIdParameter = proveedorId.HasValue ?
                new ObjectParameter("proveedorId", proveedorId) :
                new ObjectParameter("proveedorId", typeof(int));
    
            var productosParameter = productos != null ?
                new ObjectParameter("productos", productos) :
                new ObjectParameter("productos", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_RegistrarEntrada", fechaRegistroParameter, usuarioRegistroParameter, proveedorIdParameter, productosParameter);
        }
    
        public virtual int usp_RegistrarSalida(Nullable<System.DateTime> fechaRegistro, string usuarioRegistro, Nullable<int> clienteId, string productos)
        {
            var fechaRegistroParameter = fechaRegistro.HasValue ?
                new ObjectParameter("fechaRegistro", fechaRegistro) :
                new ObjectParameter("fechaRegistro", typeof(System.DateTime));
    
            var usuarioRegistroParameter = usuarioRegistro != null ?
                new ObjectParameter("usuarioRegistro", usuarioRegistro) :
                new ObjectParameter("usuarioRegistro", typeof(string));
    
            var clienteIdParameter = clienteId.HasValue ?
                new ObjectParameter("clienteId", clienteId) :
                new ObjectParameter("clienteId", typeof(int));
    
            var productosParameter = productos != null ?
                new ObjectParameter("productos", productos) :
                new ObjectParameter("productos", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_RegistrarSalida", fechaRegistroParameter, usuarioRegistroParameter, clienteIdParameter, productosParameter);
        }
    
        public virtual ObjectResult<usp_BuscarEntradaPorCodigo_Result> usp_BuscarEntradaPorCodigo(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_BuscarEntradaPorCodigo_Result>("usp_BuscarEntradaPorCodigo", codigoParameter);
        }
    
        public virtual ObjectResult<usp_BuscarSalidaPorCodigo_Result> usp_BuscarSalidaPorCodigo(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_BuscarSalidaPorCodigo_Result>("usp_BuscarSalidaPorCodigo", codigoParameter);
        }
    
        public virtual ObjectResult<usp_ListarSalidas_Result> usp_ListarSalidas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarSalidas_Result>("usp_ListarSalidas");
        }
    
        public virtual ObjectResult<usp_ListarEntradas_Result> usp_ListarEntradas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarEntradas_Result>("usp_ListarEntradas");
        }
    }
}
